spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://220.132.15.117:3306/account_book
    username: rex
    password: ji3cp4su3F*+++
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: error