spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://220.132.15.117:3306/account_book?useUnicode=true&characterEncoding=utf8
    username: rex
    password: ji3cp4su3F*+++
    initialization-mode: never
    sql-script-encoding: UTF-8
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: trace