server:
  port: 8082
spring:
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://192.168.56.1:3333/account_book
    username: rex
    password: ji394su3
    schema: classpath:/db/schema-mariadb.sql
    data: classpath:/db/data-mariadb.sql
    initialization-mode: always
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: trace